# Based on the information of barcode, split R2.fastq.gz to 96 single cell .2.fq.gz

perl=/home/wd/xinyan/Germline/Species/Homo_sapiens/RNA_UMI/splitbarcode0bp.pl
Raw_Fastq_name=DMLCX6_TKR180700197_2.fq.gz
cell_name=DMLCX6

perl $perl $Raw_Fastq_name 0 \
AACGTGAT AAACATCG ATGCCTAA AGTGGTCA ACCACTGT ACATTGGC CAGATCTG CATCAAGT CGCTGATC ACAAGCTA CTGTAGCC AGTACAAG AACAACCA AACCGAGA AACGCTTA AAGACGGA AAGGTACA ACACAGAA ACAGCAGA ACCTCCAA ACGCTCGA ACGTATCA ACTATGCA AGAGTCAA AGATCGCA AGCAGGAA AGTCACTA ATCCTGTA ATTGAGGA CAACCACA CAAGACTA CAATGGAA CACTTCGA CAGCGTTA CATACCAA CCAGTTCA CCGAAGTA CCGTGAGA CCTCCTGA CGAACTTA CGACTGGA CGCATACA CTCAATGA CTGAGCCA CTGGCATA GAATCTGA GACTAGTA GAGCTGAA GATAGACA GCCACATA GCGAGTAA GCTAACGA GCTCGGTA GGAGAACA GGTGCGAA GTACGCAA GTCGTAGA GTCTGTCA GTGTTCTA TAGGATGA TATCAGCA TCCGTCTA TCTTCACA TGAAGAGA TGGAACAA TGGCTTCA TGGTGGTA TTCACGCA AACTCACC AAGAGATC AAGGACAC AATCCGTC AATGTTGC ACACGACC ACAGATTC AGATGTAC AGCACCTC AGCCATGC AGGCTAAC ATAGCGAC ATCATTCC ATTGGCTC CAAGGAGC CACCTTAC CCATCCTC CCGACAAC CCTAATCC CCTCTATC CGACACAC CGGATTGC CTAAGGTC GAACAGGC GACAGTGC GAGTTAGC GATGAATC GCCAAGAC \
${cell_name}_sc1.2.fq.gz ${cell_name}_sc2.2.fq.gz ${cell_name}_sc3.2.fq.gz ${cell_name}_sc4.2.fq.gz ${cell_name}_sc5.2.fq.gz ${cell_name}_sc6.2.fq.gz ${cell_name}_sc7.2.fq.gz ${cell_name}_sc8.2.fq.gz ${cell_name}_sc9.2.fq.gz ${cell_name}_sc10.2.fq.gz ${cell_name}_sc11.2.fq.gz ${cell_name}_sc12.2.fq.gz ${cell_name}_sc13.2.fq.gz ${cell_name}_sc14.2.fq.gz ${cell_name}_sc15.2.fq.gz ${cell_name}_sc16.2.fq.gz ${cell_name}_sc17.2.fq.gz ${cell_name}_sc18.2.fq.gz ${cell_name}_sc19.2.fq.gz ${cell_name}_sc20.2.fq.gz ${cell_name}_sc21.2.fq.gz ${cell_name}_sc22.2.fq.gz ${cell_name}_sc23.2.fq.gz ${cell_name}_sc24.2.fq.gz ${cell_name}_sc25.2.fq.gz ${cell_name}_sc26.2.fq.gz ${cell_name}_sc27.2.fq.gz ${cell_name}_sc28.2.fq.gz ${cell_name}_sc29.2.fq.gz ${cell_name}_sc30.2.fq.gz ${cell_name}_sc31.2.fq.gz ${cell_name}_sc32.2.fq.gz ${cell_name}_sc33.2.fq.gz ${cell_name}_sc34.2.fq.gz ${cell_name}_sc35.2.fq.gz ${cell_name}_sc36.2.fq.gz ${cell_name}_sc37.2.fq.gz ${cell_name}_sc38.2.fq.gz ${cell_name}_sc39.2.fq.gz ${cell_name}_sc40.2.fq.gz ${cell_name}_sc41.2.fq.gz ${cell_name}_sc42.2.fq.gz ${cell_name}_sc43.2.fq.gz ${cell_name}_sc44.2.fq.gz ${cell_name}_sc45.2.fq.gz ${cell_name}_sc46.2.fq.gz ${cell_name}_sc47.2.fq.gz ${cell_name}_sc48.2.fq.gz ${cell_name}_sc49.2.fq.gz ${cell_name}_sc50.2.fq.gz ${cell_name}_sc51.2.fq.gz ${cell_name}_sc52.2.fq.gz ${cell_name}_sc53.2.fq.gz ${cell_name}_sc54.2.fq.gz ${cell_name}_sc55.2.fq.gz ${cell_name}_sc56.2.fq.gz ${cell_name}_sc57.2.fq.gz ${cell_name}_sc58.2.fq.gz ${cell_name}_sc59.2.fq.gz ${cell_name}_sc60.2.fq.gz ${cell_name}_sc61.2.fq.gz ${cell_name}_sc62.2.fq.gz ${cell_name}_sc63.2.fq.gz ${cell_name}_sc64.2.fq.gz ${cell_name}_sc65.2.fq.gz ${cell_name}_sc66.2.fq.gz ${cell_name}_sc67.2.fq.gz ${cell_name}_sc68.2.fq.gz ${cell_name}_sc69.2.fq.gz ${cell_name}_sc70.2.fq.gz ${cell_name}_sc71.2.fq.gz ${cell_name}_sc72.2.fq.gz ${cell_name}_sc73.2.fq.gz ${cell_name}_sc74.2.fq.gz ${cell_name}_sc75.2.fq.gz ${cell_name}_sc76.2.fq.gz ${cell_name}_sc77.2.fq.gz ${cell_name}_sc78.2.fq.gz ${cell_name}_sc79.2.fq.gz ${cell_name}_sc80.2.fq.gz ${cell_name}_sc81.2.fq.gz ${cell_name}_sc82.2.fq.gz ${cell_name}_sc83.2.fq.gz ${cell_name}_sc84.2.fq.gz ${cell_name}_sc85.2.fq.gz ${cell_name}_sc86.2.fq.gz ${cell_name}_sc87.2.fq.gz ${cell_name}_sc88.2.fq.gz ${cell_name}_sc89.2.fq.gz ${cell_name}_sc90.2.fq.gz ${cell_name}_sc91.2.fq.gz ${cell_name}_sc92.2.fq.gz ${cell_name}_sc93.2.fq.gz ${cell_name}_sc94.2.fq.gz ${cell_name}_sc95.2.fq.gz ${cell_name}_sc96.2.fq.gz ${cell_name}_noid.2.fq.gz
